[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
enableStaticServing = true
runOnSave = true
maxUploadSize = 50

[theme]
primaryColor = "#0A2239"
backgroundColor = "#0A2239"
secondaryBackgroundColor = "#2A7A7B"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
